apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
        - name: backend
          image: us-central1-docker.pkg.dev/ai-sre-platform-506305/ai-sre-images/backend:v3
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://sre_user:sre_password@postgres:5432/sre_db
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-secret
                  key: GOOGLE_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: { app: backend }
  ports:
    - { port: 8000, targetPort: 8000 }

